sudo: false
language: node_js
node_js:
- 5.6.0
env:
  global:
  - CXX=g++-4.8
  - secure: ugC5SvxJSUV886jBYTDe9k1u2o0iWAi5PDzKeqmI1bZZPQ7f5bkkYX7WCEyy4FuxPFu5dcvfVxk1pKlgc4c7tiOlkeaQxILGcrjhXVn6QYeuVKNc7s92KYsL9EDqCTt8YvVVBCdlmHTlKRDHLmlaIfGwkYCl1TbVWAlPS6Su8/rraRRyUvzRhPlltkw5Sh/nwYgRUPrGHOF+3AjVOQ+JL6zE9NrzytNr5FnAV6QI4jmR2L18TrZ/uqqN6gjug5XEmRvIzVuy6uOIOSVZPvNNhX+E5LyZgDaKU65+L72t7dIyyjtLRiHyMJyzJaMjnR5qhVbq9ldD4V/ks3P30RcYrCZjtK6f1MiLwWJeoaHE+H+LaHQcnI4b8131Xlw+lrZJrnsk8wLQwg7Q9SF0F4/yjQIL3724z5yrH3K25MXvv6lg+JKNDU+q/H8pYFHpKdufRFUrzK52G+QhWR+F/0Fk6cjIEXu0p9j7Y2i26L1DfNqqgbtgbuipUNcuOduOicmJnnMFradzWgGb9akv3jNlz0gGIyzT6oqT+mhYH2shnNvegjqNOz+mwbRAF9tx4MnQD/scYMrF7l92d98Rz7lR3QSmGFWXCALgKwAxAkslWsH/P1rTPxkvhXlZ+HC3b1rjKTGyPFMyIstDSvoYlalMdLdELWAoCvfkDE0xvMXGtI0=
  - secure: JSu0WxNJPeP2MCGfJ0v0yra3RqAwaLdK5RWPxiSlIyU3SBp2on+0PJ+8QcVSDlTUHy43yekSmy6mApCjPk/OJHyo0OPbufxHtuhmgUCc3Grz/1ez/Ssq8Jggwmw4g29W10ne/KZ1Qrf3odVk9kIsxQL37TBor6E4o+E8T7/9dyOTimQRLOjHaFibOmZeACTDPpiU9Dw/b42NibfxmofFowXeWUHAppINxuD959ExYMyxUna8YnFo5NsmWrcIWFn9bODDVravSBuSFwAErbRst+9tJIyXIyZ8h/qYrsHEGVMVKvlGNktoYkWpgICqguuAQTErF1ItpwszPq+PmpIo/aiLD6B2D/t6Q9hLxzWpxtJNY8XQyhZSu15lzL1ShGPTfoaquMelvB+wfGDIDQxJHX+AaruTLAQ1kuac8d4Y8SkSR16Dv+05RFrH7CUfBSEsIGAt5/SKD5gr0MAtbdEPcZgXwoA66eoJT5eE5x5Y4XP/y+NX205PfwpsWxxrA46fpHJj5JDF5ADoq1+Y0nGoZws8JvPuz213GKXYA7lynqVe4xilDKWXXBZFcGzZUCJ29Z5eYTL72PpG+xBxL0PWx4GJTj4zBSqO512rPEV5kjQGZJNONuT1Bkj4z88juYWYTjxyYuwkA9LX9AxmjfyYb02H2U/OIT9jj0911Cai/2U=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- npm config set progress=false
- npm install -g npm@^3
install:
- npm i
script:
- npm start
after_script:
- ./publish.sh
# Do manual under deploy `legacy` tag until babel-eslint issue resolves
# https://github.com/babel/babel-eslint/issues/249
#deploy:
  #provider: npm
  #email: dtothefp@gmail.com
  #on:
    #tags: true
  #api_key:
    #secure: gvXmuXpWAf/wiGYMgj9Bi0y8esp1WUxVo9IYtXUmFAM0nvdIA+i48JhtH8EQ2gEGAnVIytDD9UVReG2IYJ7GQgv9BE+hzgleBlqbYw8VyQmscVFtnVuafjnJf6Zr/XPTB/febOd8zlgJpblkkjUjn2lGjgsM548YmQ/cSFoy680LDvdG69j5jlLIAqD+HdVqDnVTB1Ydj8PCwYYZlLLuPSAiFs6d1ZjV8eG2GxnxxntHq0gIR3hk14RWXmYq5ZUxEePLeKyIYNlHYkCi5Q4zPHDAlTGRhKLPXZU9Y+IdhbuzaYf9nFoZSEPdFPSK11w8HooDHcqzVCxWsqNH8VcqrpPUbMhXAtVwcn5U+TjTsxECgl289XArFqIveGr7bbOrNjxZIPXt97Kk0VuxvJJGn88PIPJkx9MGbnaKpXSDjwyKwTrW9JgyYtlZjPaJH4HKla/h9jC35Qj6vID3jJUoTgiQOlKPVwdkvZ74wa85idbOUtU8eolygZHpZnJmm/hkS16WtFv++1NzqP3KyQQIU4+cechW+ZnUU5ev1D3DgXd77CMDQyNz+Z3XS2eKNE9/eQTme34b6Rqrd4C51ue3cDX+Af/AO2p5IeCbiEPRgeLBRSeoVxNNVAW6V4SP/QPTkWiqHds6JULgpwkjl3Jy5SAaMRrsDrwgMrlfHweOa9w=
